/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteEaArgs } from "./DeleteEaArgs";
import { EaCountArgs } from "./EaCountArgs";
import { EaFindManyArgs } from "./EaFindManyArgs";
import { EaFindUniqueArgs } from "./EaFindUniqueArgs";
import { Ea } from "./Ea";
import { EaService } from "../ea.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Ea)
export class EaResolverBase {
  constructor(
    protected readonly service: EaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Ea",
    action: "read",
    possession: "any",
  })
  async _easMeta(@graphql.Args() args: EaCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Ea])
  @nestAccessControl.UseRoles({
    resource: "Ea",
    action: "read",
    possession: "any",
  })
  async eas(@graphql.Args() args: EaFindManyArgs): Promise<Ea[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Ea, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Ea",
    action: "read",
    possession: "own",
  })
  async ea(@graphql.Args() args: EaFindUniqueArgs): Promise<Ea | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ea)
  @nestAccessControl.UseRoles({
    resource: "Ea",
    action: "delete",
    possession: "any",
  })
  async deleteEa(@graphql.Args() args: DeleteEaArgs): Promise<Ea | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
